#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Log-Dispatch-Array
Version  : 1.003
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Log-Dispatch-Array-1.003.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Log-Dispatch-Array-1.003.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libl/liblog-dispatch-array-perl/liblog-dispatch-array-perl_1.003-1.debian.tar.xz
Summary  : 'log events to an array (reference)'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Log-Dispatch-Array-license
Requires: perl-Log-Dispatch-Array-man
Requires: perl(B::Hooks::EndOfScope)
Requires: perl(Class::Data::Inheritable)
Requires: perl(Exception::Class)
Requires: perl(Log::Dispatch::Output)
Requires: perl(Module::Implementation)
Requires: perl(Module::Runtime)
Requires: perl(Package::Stash)
Requires: perl(Params::ValidationCompiler)
Requires: perl(Specio::Exporter)
Requires: perl(Sub::Exporter::Progressive)
Requires: perl(Sub::Identify)
Requires: perl(Test::Deep)
Requires: perl(Try::Tiny)
Requires: perl(Variable::Magic)
Requires: perl(namespace::autoclean)
Requires: perl(namespace::clean)
BuildRequires : perl(B::Hooks::EndOfScope)
BuildRequires : perl(Class::Data::Inheritable)
BuildRequires : perl(Exception::Class)
BuildRequires : perl(Log::Dispatch::Output)
BuildRequires : perl(Module::Implementation)
BuildRequires : perl(Module::Runtime)
BuildRequires : perl(Package::Stash)
BuildRequires : perl(Params::ValidationCompiler)
BuildRequires : perl(Specio::Exporter)
BuildRequires : perl(Sub::Exporter::Progressive)
BuildRequires : perl(Sub::Identify)
BuildRequires : perl(Test::Deep)
BuildRequires : perl(Try::Tiny)
BuildRequires : perl(Variable::Magic)
BuildRequires : perl(namespace::autoclean)
BuildRequires : perl(namespace::clean)

%description
This archive contains the distribution Log-Dispatch-Array,
version 1.003:
log events to an array (reference)

%package license
Summary: license components for the perl-Log-Dispatch-Array package.
Group: Default

%description license
license components for the perl-Log-Dispatch-Array package.


%package man
Summary: man components for the perl-Log-Dispatch-Array package.
Group: Default

%description man
man components for the perl-Log-Dispatch-Array package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Log-Dispatch-Array-1.003
mkdir -p %{_topdir}/BUILD/Log-Dispatch-Array-1.003/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Log-Dispatch-Array-1.003/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Log-Dispatch-Array
cp LICENSE %{buildroot}/usr/share/doc/perl-Log-Dispatch-Array/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Log/Dispatch/Array.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Log-Dispatch-Array/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Log::Dispatch::Array.3
